apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-07c8ad635831e2539
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: ""
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
  lables: 
    purpose: ebs-static
spec:
   nodeselector: 
    topology.kubernetes.io/zone=us-east-1a
   containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: ebs-static
  volumes:
    - name: ebs-static
      persistentVolumeClaim:
        claimName: ebs-static
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static
  ports:
    - name: nginx-service-port
      protocol: TCP
      port: 80
      targetPort: 80   
      nodePort: 30007