
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: "expense-ebs"
  volumeName: ebs-dynamic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic
spec:
   nodeselector: 
    topology.kubernetes.io/zone=us-east-1a
   containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: ebs-dynamic
  volumes:
    - name: ebs-dynamic
      persistentVolumeClaim:
        claimName: ebs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-dynamic
  ports:
    - name: nginx-service-port
      protocol: TCP
      port: 80
      targetPort: 80   
      nodePort: 30007