apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  csi:
    driver: efs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-08e0c4ca4aed0cfc2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  storageClassName: ""
  volumeName: efs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static
  lables: 
    purpose: efs-static
spec:
   nodeselector: 
    topology.kubernetes.io/zone=us-east-1a
   containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: efs-static
  volumes:
    - name: ebs-static
      persistentVolumeClaim:
        claimName: efs-static
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: efs-static
  ports:
    - name: nginx-service-port
      protocol: TCP
      port: 80
      targetPort: 80   
      nodePort: 30007