
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: "efs-expense"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic
  lables: 
    purpose: efs-dynamic
spec:
   containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: expense-efs
  volumes:
    - name: efs-dynamic
      persistentVolumeClaim:
        claimName: efs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: efs-dynamic
  ports:
    - name: nginx-service-port
      protocol: TCP
      port: 80
      targetPort: 80   
    