apiVersion: v1
kind: Pod
metadata:
  name: environment
spec:
  containers:
  # docker run -d  --name nginx nginx
  - name: nginx
    image: nginx  
    env: 
      - name: course
        value: "devops"
      - name: trainer
        value: "shivakumar reddy"
      - name: duration
        value: "120hrs"