apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  # docker run -d  --name nginx nginx
  - name: nginx
    image: nginx  
    env: 
      - name: course
        valueFrom:
          configMapKeyRef:
            name: nginx-config
            key: course
      - name: duration
        valueFrom:
          configMapKeyRef:
            name: nginx-config
            key: duration