apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
  # docker run -d  --name nginx nginx
  - name: nginx
    image: nginx  
    envFrom:
    - secretRef:
        name: pod-secret
        
        