apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels: # these are replicaset lables
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
  # these are used to select the pod to create replicas
    matchLabels:
      app: nginx
      tier: frontend
  # this is pod definition
  template:
    metadata:
    # these lables belongs to pod
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    tier: frontend
    app: nginx
  ports:
    - name: nginx-service-port
      protocol: TCP
      port: 80
      targetPort: 80   